name: Automatically publish extension to Chrome Web Store

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to Chrome Web Store
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'extension')
    steps:
      - uses: actions/checkout@v2
      - name: Zip extension
        run: zip -r extension.zip extension
      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          extension-id: ${{ vars.EXTENSION_ID }}
          client-id: ${{ secrets.EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.EXTENSION_CLIENT_SECRET }}
          refresh-token: ${{ secrets.EXTENSION_REFRESH_TOKEN }}
          file-path: extension.zip
      - uses: actions/upload-artifact@v2
        with:
          name: extension
          path: extension.zip
