name: Scrape

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
    
      
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          cd ./scraper
          npm install
          npx prisma generate
          npm run start
