name: Deploy website -not complete -do not use
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          cd ./server
          npm install
          npx prisma generate
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./server/dist
  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        node-version: [19.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: server
          path: ./server/dist
      - name: Move server
        run: |
          cd ./server
          rsync -av --progress --exclude='src' --exclude='node_modules' ./ /etc/anticlickbait/www

      - name: npm install, build
        run: |
          cd /etc/anticlickbait/www
          npm install
          npx prisma generate
          npm run build
      - name: pm2 restart if exists else start
        run: |
          cd /etc/anticlickbait/www
          pm2 restart anticlickbait || pm2 start npm --name anticlickbait -- start
