name: Deploy website -not complete -do not use
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Echo account name linux
        run: whoami
