name: Deploy website -not complete -do not use
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [19.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PRIVATE_KEY_PATH: ${{ secrets.PRIVATE_KEY_PATH }}
      CERTIFICATE_PATH: ${{ secrets.CERTIFICATE_PATH }}
      DEPLOYMENT_PATH: ~/www
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          cd ./server
          npm install
          npx prisma generate
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: ./server/dist
  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        node-version: [19.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PRIVATE_KEY_PATH: ${{ secrets.PRIVATE_KEY_PATH }}
      CERTIFICATE_PATH: ${{ secrets.CERTIFICATE_PATH }}
      DEPLOYMENT_PATH: /home/anticlickbait/www
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: server
          path: ./server/dist
      - name: Move server
        run: |
          cd ./server
          mkdir -p $DEPLOYMENT_PATH
          rsync -av --progress --exclude='node_modules' ./ $DEPLOYMENT_PATH
      - name: npm install, build
        run: |
          cd $DEPLOYMENT_PATH
          npm install
          npx prisma generate
          npm run build
      - name: pm2 restart if exists else start
        env:
          PORT: 30000
          # set database url
        run: |
          cd $DEPLOYMENT_PATH
          pm2 restart anticlickbait --update-env || pm2 start npm --name anticlickbait -- start -- --port $PORT --DATABASE_URL $DATABASE_URL  --PRIVATE_KEY_PATH $PRIVATE_KEY_PATH --CERTIFICATE_PATH $CERTIFICATE_PATH
